#ifndef INPUTDEFINITIONS_HPP
#define INPUTDEFINITIONS_HPP

#include "SDL.hpp"
#include "SDL.h"

#define KEYBOARD_SIZE 282

enum KeyboardKey
{
	KEY_ESCAPE = SDL_SCANCODE_ESCAPE,
	KEY_RIGHT  = SDL_SCANCODE_RIGHT,
	KEY_LEFT   = SDL_SCANCODE_LEFT
};

#endif //INPUTDEFINITIONS_HPP